warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/BETA4_ANDROID_REVIEW.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/BETA4_QUALITY_REPORT.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/DATABASE_DESIGN.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/PRODUCT_REQUIREMENTS.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/V1_SCOPE.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'docs/WEB_TO_LOCAL_PORT.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/android/app/build.gradle', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/android/app/capacitor.build.gradle', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/android/capacitor.settings.gradle', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/tests/e2e/ui-smoke.mjs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/tests/five-option-rating.test.mjs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/tests/local-v1-services.test.mjs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/tests/repository.test.mjs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/tests/shell.test.mjs', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/app.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/app.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/backup-service.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/beer-repository.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/local.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/photo-repository.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/assets/tasting-repository.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'mobile/web/index.html', LF will be replaced by CRLF the next time Git touches it
