# Generated by Django 5.2.16 on 2026-07-12 02:53

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('normalized_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beer_styles',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FlavorTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'flavor_tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TastingTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tasting_tags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', '国家代码必须为两个大写英文字母。')])),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'country_code', 'region'), name='brand_normalized_location_unique')],
            },
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(max_length=200)),
                ('country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', '国家代码必须为两个大写英文字母。')])),
                ('region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'breweries',
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'country_code', 'region'), name='brewery_normalized_location_unique')],
            },
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('origin_country_code', models.CharField(blank=True, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', '国家代码必须为两个大写英文字母。')])),
                ('origin_region', models.CharField(blank=True, max_length=120)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('ibu', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('color_ebc', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('catalog_notes', models.TextField(blank=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='core.beerstyle')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='core.brand')),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beers', to='core.brewery')),
            ],
            options={
                'db_table': 'beers',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BeerFlavorTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_tag_links', to='core.beer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beer_links', to='core.flavortag')),
            ],
            options={
                'db_table': 'beer_flavor_tags',
            },
        ),
        migrations.CreateModel(
            name='RatingDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]+$', '评分维度代码只能使用小写字母、数字和下划线。')])),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('scale_min', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('scale_max', models.DecimalField(decimal_places=3, default=Decimal('10'), max_digits=6)),
                ('step', models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=6)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'rating_dimensions',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('scale_min__lt', models.F('scale_max'))), name='rating_scale_min_lt_max'), models.CheckConstraint(condition=models.Q(('step__gt', 0)), name='rating_step_positive')],
            },
        ),
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tasted_at', models.DateTimeField()),
                ('drinking_location', models.CharField(blank=True, max_length=255)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency_code', models.CharField(default='CNY', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', '货币代码必须为三个大写英文字母。')])),
                ('purchase_channel', models.CharField(blank=True, max_length=100)),
                ('purchase_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))])),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tastings', to='core.beer')),
            ],
            options={
                'db_table': 'tastings',
                'ordering': ['-tasted_at', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('thumbnail_key', models.CharField(max_length=500, unique=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('tasting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.tasting')),
            ],
            options={
                'db_table': 'photos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TastingRatingValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dimension_name_snapshot', models.CharField(max_length=80)),
                ('scale_min_snapshot', models.DecimalField(decimal_places=3, max_digits=6)),
                ('scale_max_snapshot', models.DecimalField(decimal_places=3, max_digits=6)),
                ('step_snapshot', models.DecimalField(decimal_places=3, max_digits=6)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rating_values', to='core.ratingdimension')),
                ('tasting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_values', to='core.tasting')),
            ],
            options={
                'db_table': 'tasting_rating_values',
            },
        ),
        migrations.CreateModel(
            name='TastingTagLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_links', to='core.tastingtag')),
                ('tasting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='core.tasting')),
            ],
            options={
                'db_table': 'tasting_tag_links',
            },
        ),
        migrations.AddIndex(
            model_name='beer',
            index=models.Index(fields=['origin_country_code'], name='beers_origin__36281d_idx'),
        ),
        migrations.AddIndex(
            model_name='beer',
            index=models.Index(fields=['style'], name='beers_style_i_0f88d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.CheckConstraint(condition=models.Q(('abv__isnull', True), models.Q(('abv__gte', 0), ('abv__lte', 100)), _connector='OR'), name='beer_abv_range'),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.CheckConstraint(condition=models.Q(('ibu__isnull', True), ('ibu__gte', 0), _connector='OR'), name='beer_ibu_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.CheckConstraint(condition=models.Q(('color_ebc__isnull', True), ('color_ebc__gte', 0), _connector='OR'), name='beer_color_ebc_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='beerflavortag',
            constraint=models.UniqueConstraint(fields=('beer', 'tag'), name='beer_flavor_tag_unique'),
        ),
        migrations.AddIndex(
            model_name='tasting',
            index=models.Index(fields=['beer', '-tasted_at', '-created_at'], name='tastings_beer_id_28de0f_idx'),
        ),
        migrations.AddIndex(
            model_name='tasting',
            index=models.Index(fields=['-tasted_at'], name='tastings_tasted__4e7031_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(condition=models.Q(('volume_ml__isnull', True), ('volume_ml__gt', 0), _connector='OR'), name='tasting_volume_positive'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__isnull', True), ('price_amount__gte', 0), _connector='OR'), name='tasting_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(condition=models.Q(('overall_score__isnull', True), models.Q(('overall_score__gte', 0), ('overall_score__lte', 10)), _connector='OR'), name='tasting_overall_score_range'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['tasting', 'sort_order', 'created_at'], name='photos_tasting_e5a28c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tastingratingvalue',
            constraint=models.UniqueConstraint(fields=('tasting', 'dimension'), name='tasting_dimension_unique'),
        ),
        migrations.AddConstraint(
            model_name='tastingtaglink',
            constraint=models.UniqueConstraint(fields=('tasting', 'tag'), name='tasting_tag_unique'),
        ),
    ]
