# Generated by Django 5.2.16 on 2026-07-12 06:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


def migrate_v2_reference_data(apps, schema_editor):
    BeerCategory = apps.get_model("core", "BeerCategory")
    BeerStyle = apps.get_model("core", "BeerStyle")
    FlavorTag = apps.get_model("core", "FlavorTag")
    BeerFlavorTag = apps.get_model("core", "BeerFlavorTag")

    category_specs = {
        "lager": ("Lager", "Lager", 0),
        "ale": ("Ale", "Ale", 1),
    }
    categories = {}
    for code, (name, normalized_name, sort_order) in category_specs.items():
        categories[code], _ = BeerCategory.objects.get_or_create(
            code=code,
            defaults={"name": name, "normalized_name": normalized_name, "sort_order": sort_order, "is_active": True},
        )

    lager_names = {"lager", "皮尔森", "淡色拉格", "黑拉格", "pilsner", "pils"}
    for style in BeerStyle.objects.all().order_by("created_at", "id"):
        value = (style.normalized_name or style.name).strip().casefold()
        category = categories["lager"] if value in lager_names else categories["ale"]
        style.category_id = category.id
        style.save(update_fields=["category"])

    initial_styles = (
        ("pilsner", "皮尔森", "lager"),
        ("pale_lager", "淡色拉格", "lager"),
        ("dark_lager", "黑拉格", "lager"),
        ("ipa", "IPA", "ale"),
        ("wheat", "小麦啤酒", "ale"),
        ("stout", "世涛", "ale"),
    )
    for code, name, category_code in initial_styles:
        BeerStyle.objects.get_or_create(
            normalized_name=code,
            defaults={"name": name, "category_id": categories[category_code].id, "is_active": True},
        )

    # Normalize existing tags while preserving the first tag and all relations.
    tags = list(FlavorTag.objects.all().order_by("created_at", "id"))
    for tag in tags:
        tag.normalized_name = f"legacy-{tag.pk}"
        tag.save(update_fields=["normalized_name"])
    kept = {}
    for tag in tags:
        import re
        import unicodedata
        normalized = re.sub(r"\s+", " ", unicodedata.normalize("NFKC", tag.name or "").strip()).casefold()
        if not normalized:
            normalized = f"legacy-{tag.pk}"
        if normalized in kept:
            primary = kept[normalized]
            for link in list(BeerFlavorTag.objects.filter(tag_id=tag.pk)):
                if BeerFlavorTag.objects.filter(beer_id=link.beer_id, tag_id=primary.pk).exists():
                    link.delete()
                else:
                    link.tag_id = primary.pk
                    link.save(update_fields=["tag"])
            tag.delete()
        else:
            tag.normalized_name = normalized
            tag.save(update_fields=["normalized_name"])
            kept[normalized] = tag

    Tasting = apps.get_model("core", "Tasting")
    for tasting in Tasting.objects.all():
        value = (tasting.purchase_channel or "").strip().casefold()
        if value in {"线上", "网购", "online"}:
            tasting.purchase_channel = "online"
        elif value in {"线下", "超市", "酒吧", "测试超市", "offline"}:
            tasting.purchase_channel = "offline"
        elif value in {"赠送", "朋友赠送", "gift"}:
            tasting.purchase_channel = "gift"
        tasting.save(update_fields=["purchase_channel"])


def reverse_v2_reference_data(apps, schema_editor):
    # Reference data and normalized tags are intentionally retained on rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('normalized_name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'beer_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='tasting',
            name='tasting_volume_positive',
        ),
        migrations.RenameField(
            model_name='tasting',
            old_name='volume_ml',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='beer',
            name='mouthfeel_profile',
            field=models.CharField(blank=True, choices=[('crisp', '清爽'), ('balanced', '适中'), ('full', '醇厚')], max_length=20),
        ),
        migrations.AddField(
            model_name='beer',
            name='plato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='tasting',
            name='bottle_count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tasting',
            name='purchase_channel',
            field=models.CharField(blank=True, choices=[('online', '线上'), ('offline', '线下'), ('gift', '赠送')], max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='tasting_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tasting',
            constraint=models.CheckConstraint(condition=models.Q(('bottle_count__isnull', True), ('bottle_count__gt', 0), _connector='OR'), name='tasting_bottle_count_positive'),
        ),
        migrations.AddField(
            model_name='beerstyle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='core.beercategory'),
        ),
        migrations.RunPython(migrate_v2_reference_data, reverse_v2_reference_data),
        migrations.AlterField(
            model_name='beerstyle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='core.beercategory'),
        ),
    ]
